name:                hw2
version:             0.1.0.0
github:              "Kvel4/fp-test-hw2"
license:             GPL-3
author:              "Monakhov Daniil"
maintainer:          "d.monakhov0@gmail.com"
copyright:           "2021 Monakhov Daniil"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hw2#readme>
homepage:       https://github.com/githubuser/hw2#readme

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: scientific

executables:
  hw2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw2
